CREATE TABLE IF NOT EXISTS bokings (
		id INTEGER  PRIMARY KEY AUTOINCREMENT,
		Seat_number  INTEGER NOT NULL UNIQUE 
					CHECK (seat_number BETWEEN 1 AND 13), 
		passenger_name  TEXT NOT NULL
		phone		TEXT NOT NULL
		create_at	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);